Yokota/add configscript
Nishida-Lab/robot_self_filter pull request #4
Opened 2019-07-18 15:12 UTC by AtsukiYokota

[#13](https://github.com/Nishida-Lab/denso_moveit/issues/13)についてです．
ローカルCIは通っています．

2019-07-18 15:47 UTC, MoriKen254 requested changes
こちらのコードはforkしているという事情もあると思い、あまり中には触れません。CMakeListsのフォーマットだけ、catkin_lint も参考に確認願います。

2019-07-18 15:47 UTC, MoriKen254 commented on CMakeLists.txt
> +endforeach(scripts)
endforeach 後の () は空で良いようです。明記したいならコメントで付与するほうがベター。

2019-07-18 15:47 UTC, MoriKen254 commented on CMakeLists.txt
> +endforeach(scripts)
98 行目の endforeach(dirs) ついても同様です。

2019-07-19 11:32 UTC, AtsukiYokota commented on CMakeLists.txt
> +endforeach(scripts)
こちらも修正しました．

2019-07-19 11:51 UTC, MoriKen254 approved these changes
いいと思います！Travis も通りました。

Approve!

2019-07-19 11:52 UTC, merged